# Generated by Django 2.2 on 2019-06-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adult_Products',
            new_name='Adult_Product',
        ),
        migrations.RenameModel(
            old_name='Essential_Oils',
            new_name='Essential_Oil',
        ),
        migrations.RenameModel(
            old_name='Smart_Watches',
            new_name='Smart_Watch',
        ),
    ]
