# Generated by Django 2.2 on 2019-06-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190608_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smart_Watch',
            new_name='Smart_Watche',
        ),
    ]
