# Generated by Django 2.2 on 2019-06-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190608_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smart_Watche',
            new_name='Smart_Watch',
        ),
    ]
