# Generated by Django 2.2 on 2019-06-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190608_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult_product',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='essential_oil',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
